---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: "C: /Users/USER/Desktop/svm-r-markdown-templates-master/svm-latex-cv.tex"
geometry: margin=1in

title: "CV"
author: Selcen Cakir


address: "Bogazici University · Department of Economics · Natuk Birkan Building 214  · Istanbul 34342, Turkey"
fontawesome: yes
email: selcencakir1@gmail.com
# github: svmiller
phone: "+90 (212) 359 7651"
web: selcencakir.github.io
updated: "October 2019"

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Academic Positions

*Bogazici University, Department of Economics*

Assistant Professor \hfill Sep 2018 (expected)-



# Education

*Ph.D. University of Virginia*, Economics \hfill May 2018 
*M.A. University of Virginia*, Economics \hfill 2012
*M.A. Koc University*, Economics \hfill 2011
*B.A. TOBB ETU*, Economics \hfill 2008



# Research Papers

## Working Papers

Choosing Your Pond: A Structural Model of Political Power Sharing.

## Ongoing Projects (_titles are suggestive_)

Bounding Bias Caused by Left-Censoring in Survival Models (with [Steven Stern](https://sites.google.com/site/stevensterneconomics/home))

Conflict over Natural Resources (with Peter Debaere)

Superstar Firms and Job Creation



## Other Publications

Student. 1905. "The Pearson Co-efficient of Correlation." Supplement to Report of 1904, Arthur Guinness Son & Company.

Student. 1904. "The Application of the 'Law of Error' to the Work of the Brewery." Report, Arthur Guinness Son & Company.

# References

Available upon request, though likely would include Karl Pearson and Ronald A. Fisher. Please send corrections, feedback, or details of missed publications (of which there are probably a few) to svmille@clemson.edu.
